name: NotebookEnvironment
channels:
  - conda-forge
dependencies:
  - gcc
  - matplotlib=3.0
  - python=3.7
  - ipywidgets=7.4
  - jupyter=1.0
  - notebook=5.7
  - numpy=1.15
  - openpyxl=2.5
  - pandas=0.23
  - pip=18.1
  - scipy=1.1
  - seaborn=0.9
  - plotly=3.4.2
  - pytables=3.4.4
  - pip
  - xlrd
  - cryptography=2.3